import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import axios from 'axios'


//import styles from '../styles/Home.module.css'

const Home = () => {


  const [news, setNews] = useState<any>([]);

  const getNews = () => {
    setNews('fds');
    console.log(news);
  }

  //mounted
  useEffect(()=> {
    getNews;
    console.log('fd');
  },[])

  return (
    <div>
      <Head>
        <title>ホーム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>


      </div>
    </div>
  )
}

export default Home
